defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: toolbelt_dev
  password: 88as4685

development:
  <<: *defaults
  database: toolbelt_dev

test:
  <<: *defaults
  database: toolbelt_dev