<%
  # http://mislav.uniqpath.com/rails/branching-the-database-along-with-your-code/
  branch = `git symbolic-ref HEAD 2>/dev/null`.chomp.sub('refs/heads/', '').split('/')
  suffix = branch.first == 'feature' && `git config --bool branch.#{branch.last}.database`.chomp == 'true' ? "_#{branch.last}" : ""
%>
defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: toolbelt
  password: 88as4685

development:
  <<: *defaults
  database: toolbelt_dev

test:
  <<: *defaults
  database: toolbelt_test